package config

type DB struct {
	AccountsCollection          string
	ActivitiesCollection        string
	AnalyticsCollection         string
	AppealsCollection           string
	ArtistEventsCollection      string
	ArtistsCollection           string
	BaitoApplicationsCollection string
	BaitoCollection             string
	BaitoWorkerCollection       string
	BlogPostsCollection         string
	BookingsCollection          string
	BehindTheScenesCollection   string
	CartCollection              string
	CatalogueCollection         string
	ChatsCollection             string
	CommentsCollection          string
	CouponCollection            string
	CropsCollection             string
	DateCapsCollection          string
	EventsCollection            string
	FarmsCollection             string
	FundingCollection           string
	FeedPostsCollection         string
	FilesCollection             string
	FollowingsCollection        string
	FarmOrdersCollection        string
	HashtagCollection           string
	IdempotencyCollection       string
	ItineraryCollection         string
	JournalCollection           string
	LikesCollection             string
	MapsCollection              string
	MediaCollection             string
	MenuCollection              string
	MerchCollection             string
	MerechatCollection          string
	MessagesCollection          string
	ModeratorApplications       string
	NoticesCollection           string
	OrderCollection             string
	PlacesCollection            string
	ProductCollection           string
	PurchasedTicketsCollection  string
	RecipeCollection            string
	RefundsCollection           string
	ReportsCollection           string
	ReviewsCollection           string
	ServiceCollection           string
	SettingsCollection          string
	SlotCollection              string
	SongsCollection             string
	StripeOrdersCollection      string
	SubscribersCollection       string
	TicketsCollection           string
	TiersCollection             string
	TransactionCollection       string
	UserDataCollection          string
	UserCollection              string
	AlbumsCollection            string
	PlaylistsCollection         string
	GlobalLedgerCollection      string
}

var Collections = DB{
	AccountsCollection:          "accounts",
	ActivitiesCollection:        "activities",
	AnalyticsCollection:         "analytics",
	AppealsCollection:           "appeals",
	ArtistEventsCollection:      "artistevents",
	ArtistsCollection:           "artists",
	BaitoApplicationsCollection: "baitoapply",
	BaitoCollection:             "baitos",
	BaitoWorkerCollection:       "baitoworkers",
	BlogPostsCollection:         "blogposts",
	BookingsCollection:          "bookings",
	BehindTheScenesCollection:   "bts",
	CartCollection:              "cart",
	CatalogueCollection:         "catalogue",
	ChatsCollection:             "chats",
	CommentsCollection:          "comments",
	CouponCollection:            "coupons",
	CropsCollection:             "crops",
	DateCapsCollection:          "date_caps",
	EventsCollection:            "events",
	FarmsCollection:             "farms",
	FundingCollection:           "funding",
	FeedPostsCollection:         "feedposts",
	FilesCollection:             "files",
	FollowingsCollection:        "followings",
	FarmOrdersCollection:        "forders",
	HashtagCollection:           "hashtags",
	IdempotencyCollection:       "idempotency",
	ItineraryCollection:         "itinerary",
	JournalCollection:           "journals",
	LikesCollection:             "likes",
	MapsCollection:              "maps",
	MediaCollection:             "media",
	MenuCollection:              "menu",
	MerchCollection:             "merch",
	MerechatCollection:          "merechats",
	MessagesCollection:          "messages",
	ModeratorApplications:       "modapps",
	NoticesCollection:           "notices",
	OrderCollection:             "orders",
	PlacesCollection:            "places",
	ProductCollection:           "products",
	PurchasedTicketsCollection:  "purticks",
	RecipeCollection:            "recipes",
	ReportsCollection:           "reports",
	RefundsCollection:           "refunds",
	ReviewsCollection:           "reviews",
	ServiceCollection:           "service",
	SettingsCollection:          "settings",
	SlotCollection:              "slots",
	SongsCollection:             "songs",
	StripeOrdersCollection:      "stripeorders",
	SubscribersCollection:       "subscribers",
	TicketsCollection:           "ticks",
	TiersCollection:             "tiers",
	TransactionCollection:       "transactions",
	UserDataCollection:          "userdata",
	UserCollection:              "users",
	AlbumsCollection:            "albums",
	PlaylistsCollection:         "playlists",
	GlobalLedgerCollection:      "globalledger",
}
